version: '3.4'

services:
  web:
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      GUNICORN_CMD_ARGS: "--reload --bind :8001"
      AUTH_DISABLED: "yes"
      DB_USERNAME: KnoweakAppUser
      DB_PASSWORD: app_pass
      DB_NAME: knoweak

  database:
    volumes:
      - ./db/scripts/init-dev/10-create-dev-users.sql:/docker-entrypoint-initdb.d/10.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"