version: '3'

services:
  web:
    build: .
    depends_on:
      - database
    ports:
     - "8000:8000"
    volumes:
     - .:/code
    env_file:
      - .env
    environment:
      DB_HOST: database
      DB_PORT: 3306

  database:
    image: "mysql/mysql-server:5.7"
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"

volumes:
  db-data:
    external: true
    name: mysql1-vol
