version: '3.4'

services:
  web:
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      GUNICORN_CMD_ARGS: "--reload --bind :8001"

  database:
    volumes:
      - ./db/scripts/create-dev-user.sql:/docker-entrypoint-initdb.d/10.sql
    environment:
      MYSQL_ROOT_PASSWORD: root