version: '3.4'

services:
  web:
    build: .
    depends_on:
      - database
    ports:
      - "8001:8001"
    environment:
      GUNICORN_CMD_ARGS: "--bind :8001"
      DB_HOST: database
      DB_PORT: 3306

  database:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf
      - ./db/scripts/init:/docker-entrypoint-initdb.d

volumes:
  db-data:
