version: '3.4'

services:
  web:
    volumes:
      - .:/code
    env_file:
      - .env

  database:
    volumes:
      - ./db/script-create-database.sql:/docker-entrypoint-initdb.d/01.sql
      - ./db/script-insert-seed-data.sql:/docker-entrypoint-initdb.d/02.sql
      - ./db/script-create-dev-users.sql:/docker-entrypoint-initdb.d/03.sql
    environment:
      MYSQL_ROOT_PASSWORD: root